baseURL = "https://freenet.org"
languageCode = "en-us"
title = "Freenet"
theme = "your-theme-name"

# Enable syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    style = "base16-ocean-dark"

# Enable Sass/SCSS
[params]
  compile_sass = true

# Configure the blog section
[outputs]
  section = ["HTML", "RSS"]
