baseURL = "https://freenet.org"
languageCode = 'en-us'
title = 'Freenet'
theme = "freenet"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Get Started"
    url = "/get-started/"
    weight = 2

  [[menu.main]]
    name = "Developers"
    url = "/dev/"
    weight = 3

  [[menu.main]]
    name = "Platform"
    url = "/dev/platform/"
    weight = 4
    parent = "Developers"

  [[menu.main]]
    name = "Apps"
    url = "/dev/apps/"
    weight = 5
    parent = "Developers"

  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 6

  [[menu.main]]
    name = "FAQ"
    url = "/resources/faq/"
    weight = 7
    parent = "Resources"

  [[menu.main]]
    name = "Blog"
    url = "/resources/blog/"
    weight = 8
    parent = "Resources"

  [[menu.main]]
    name = "History"
    url = "/resources/history/"
    weight = 9
    parent = "Resources"


  [[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 11
