baseURL = "https://freenet.org/"
languageCode = 'en-us'
title = 'Freenet'
theme = "freenet"

# Enable RSS feed generation
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

# Configure RSS feed
[outputFormats.RSS]
  mediatype = "application/rss+xml"
  baseName = "feed"

[services.rss]
  limit = 20 # Number of items in the feed

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Developers"
    url = "/dev/"
    weight = 3

  [[menu.main]]
    name = "Core"
    url = "/dev/core/"
    weight = 4
    parent = "Developers"

  [[menu.main]]
    name = "Apps"
    url = "/dev/apps/"
    weight = 5
    parent = "Developers"

  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 6

  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 7
    parent = "Resources"

  [[menu.main]]
    name = "Video Talks"
    url = "/resources/video-talks/"
    weight = 8
    parent = "Resources"

  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 9
    parent = "Resources"

  [[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 10

  [[menu.main]]
    name = "Ghost Key"
    weight = 11

  [[menu.main]]
    name = "Get Your Key"
    url = "/ghostkey/create"
    parent = "Ghost Key"

  [[menu.main]]
    name = "Use your Key"
    url = "/ghostkey/use"
    parent = "Ghost Key"

  [[menu.main]]
    name = "Developers"
    url = "/ghostkey/dev/"

[params]
  stripePublishableKeyTest = "pk_test_51PUf6RCCPv9UL23G0yLdnS51VCStEcnqzd2AftFWiXAOjFOgonYRRBL6F5eKOCrr2yuEHCBDqqYa8H0w7ouRyW6d00awdNMKsf"
  stripePublishableKeyLive = "pk_live_51PUf6RCCPv9UL23Gw8QzBFY3LxQMWmw2qp9k2MOyJQpaAPF5jpomsZ5K81JDvG8BW05PSqm2LjjGqfaepzHNWk8y007raWcjJX"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
