baseURL = "https://freenet.org/"
languageCode = 'en-us'
title = 'Freenet'
theme = "freenet"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Developers"
    url = "/dev/"
    weight = 3

  [[menu.main]]
    name = "Core"
    url = "/dev/core/"
    weight = 4
    parent = "Developers"

  [[menu.main]]
    name = "Apps"
    url = "/dev/apps/"
    weight = 5
    parent = "Developers"

  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 6

  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 7
    parent = "Resources"

  [[menu.main]]
    name = "Video Talks"
    url = "/resources/video-talks/"
    weight = 8
    parent = "Resources"

  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 9
    parent = "Resources"

  [[menu.main]]
    name = "Donate"
    url = "/donate/"
    weight = 10

  [[menu.main]]
    name = "History"
    url = "/resources/history/"
    weight = 11
    parent = "Resources"

