baseURL = "https://freenet.org/"
languageCode = 'en-us'
title = 'Freenet'
theme = "freenet"

# Enable RSS feed generation
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

# Configure RSS feed
[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "feed"

[services.rss]
  limit = 20 # Number of items in the feed

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

# Tutorial
  [[menu.main]]
    name = "Visit"
    url = "/use/"
    weight = 1

  [[menu.main]]
    name = "Install"
    url = "/use/platform/"
    weight = 1
    parent = "Visit"

# Guide
  [[menu.main]]
    name = "Dev"
    url = "/dev/"
    weight = 2

  [[menu.main]]
    name = "Apps"
    url = "/dev/apps/"
    weight = 1
    parent = "Dev"

  [[menu.main]]
    name = "Get Ghost Key"
    weight = 2
    url= "/dev/ghostkey/"
    parent = "Dev"

  [[menu.main]]
    name = "University"
    url = "/dev/university/"
    weight = 3
    parent = "Dev"
    
# Dev api reference
  [[menu.main]]
    name = "Reference"
    url = "/api-ref/"
    weight = 3
    
# Explanation
  [[menu.main]]
    name = "Goals"
    url = "/"
    weight = 4

  [[menu.main]]
    name = "Video Talks About the goals of freenet"
    url = "/goals/video-talks/"
    weight = 1
    parent = "Goals"
    
  [[menu.main]]
    name = "News"
    url = "/goals/news/"
    weight = 2
    parent = "Goals"

  [[menu.main]]
    name = "FAQ"
    url = "/goals/faq/"
    weight = 3
    parent = "Goals"

  [[menu.main]]
    name = "Donate"
    url = "/goals/donate/"
    weight = 4
    parent = "Goals"

[params]
  stripePublishableKeyTest = "pk_test_51PUf6RCCPv9UL23G0yLdnS51VCStEcnqzd2AftFWiXAOjFOgonYRRBL6F5eKOCrr2yuEHCBDqqYa8H0w7ouRyW6d00awdNMKsf"
  stripePublishableKeyLive = "pk_live_51PUf6RCCPv9UL23Gw8QzBFY3LxQMWmw2qp9k2MOyJQpaAPF5jpomsZ5K81JDvG8BW05PSqm2LjjGqfaepzHNWk8y007raWcjJX"

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:year/:month/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
