[package]
name = "gkwasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.92"
ghostkey = { path = "../cli" }
js-sys = "0.3.69"
blind-rsa-signatures = "0.15.1"
rand = { version = "0.8.5", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.42"

[features]
default = ["wasm-support"]
wasm-support = []
