[package]
name = "rocket-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-stripe = { version = "0.37.1", features = ["runtime-tokio-hyper"] }
dotenv = "0.15.0"
dotenv = "0.15.0"
