[package]
name = "ghostkey"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = "0.13.2"
base64 = "0.22.1"
rand_core = "0.6"
clap = "4.5.8"
rmp-serde = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
colored = "2.0"
log = "0.4.20"
serde_json = "1.0"
sha2 = "0.10"
env_logger = "0.11.3"
rand = "0.8.5"

[[bin]]
name = "ghostkey"
path = "src/bin/ghostkey.rs"

[lib]
name = "ghostkey"
path = "src/lib.rs"
