[package]
name = "ghostkey"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
p256 = "0.13.2"
base64 = "0.22.1"
rand_core = "0.6"
clap = "4.5.8"
rmp-serde = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
colored = "2.0"
