[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
p256 = "0.13.2"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rmp-serde = "1.3.0"
sha2 = "0.10"
