name: Freenet Deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Cache Hugo resources
        uses: actions/cache@v3
        env:
          cache-name: cache-hugo-resources
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Add WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack and wasm-bindgen-cli
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cargo install wasm-bindgen-cli

      - name: Install cargo-make
        run: cargo install --debug cargo-make

      - name: Build Site
        run: cargo make build-site

      - name: Debug WebAssembly files
        run: |
          echo "Contents of hugo-site/static/wasm:"
          ls -la hugo-site/static/wasm
          echo "Contents of hugo-site/public/wasm:"
          ls -la hugo-site/public/wasm
          echo "Contents of hugo-site/public:"
          ls -la hugo-site/public

      - name: Verify WebAssembly files in build
        run: |
          if [ -f hugo-site/public/wasm/gkwasm.js ]; then
            echo "gkwasm.js is present in the build"
          else
            echo "gkwasm.js is missing from the build"
            exit 1
          fi
          if [ -f hugo-site/public/wasm/gkwasm_bg.wasm ]; then
            echo "gkwasm_bg.wasm is present in the build"
          else
            echo "gkwasm_bg.wasm is missing from the build"
            exit 1
          fi

      - name: Ensure WebAssembly files are in the public directory
        run: |
          mkdir -p hugo-site/public/wasm
          cp hugo-site/static/wasm/gkwasm.js hugo-site/public/wasm/
          cp hugo-site/static/wasm/gkwasm_bg.wasm hugo-site/public/wasm/

      - name: Add wasm files to Git
        run: |
          cd hugo-site/public
          git add -f wasm/gkwasm.js wasm/gkwasm_bg.wasm
          git status

      # Stash changes to avoid conflicts when checking out gh-pages
      - name: Stash Local Changes
        run: git stash --include-untracked

      - name: Deploy Hugo Site
        env:
          HUGO_ENV: production
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-site/public
          cname: freenet.org
          force_orphan: false  # Set to false to retain history
          keep_files: true     # Set to true to keep existing files
          exclude_assets: ''

      # Remove stash (optional step)
      - name: Restore Local Changes
        run: git stash pop || echo "No stash to pop"

      - name: Verify deployment
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of root directory in gh-pages branch:"
          ls -la
          echo "Contents of wasm directory in gh-pages branch:"
          ls -la wasm || echo "wasm directory not found"
          if [ ! -f wasm/gkwasm.js ] || [ ! -f wasm/gkwasm_bg.wasm ]; then
            echo "WebAssembly files are missing from the gh-pages branch"
            exit 1
          fi

      - name: Verify gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of wasm directory in gh-pages branch:"
          ls -la wasm
          if [ ! -f wasm/gkwasm.js ] || [ ! -f wasm/gkwasm_bg.wasm ]; then
            echo "WebAssembly files are missing from the gh-pages branch"
            exit 1
          fi
