name: Freenet Deploy

on:
  push:
    branches:
      - main  # Deploy when pushing to main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # Setup Hugo for static site generation
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Setup Rust environment
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Add WebAssembly target for Rust
      - name: Add WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      # Install WebAssembly tools
      - name: Install wasm-pack and wasm-bindgen-cli
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cargo install wasm-bindgen-cli

      # Install cargo-make for building
      - name: Install cargo-make
        run: cargo install --debug cargo-make

      # Build the site using cargo-make
      - name: Build Site
        run: cargo make build-site

      # Debugging: Check the contents of WebAssembly files
      - name: Debug WebAssembly files
        run: |
          echo "Contents of hugo-site/static/wasm:"
          ls -la hugo-site/static/wasm
          echo "Contents of hugo-site/public/wasm:"
          ls -la hugo-site/public/wasm
          echo "Contents of hugo-site/public:"
          ls -la hugo-site/public

      # Verify WebAssembly files are in place
      - name: Verify WebAssembly files in build
        run: |
          if [ -f hugo-site/public/wasm/gkwasm.js ]; then
            echo "gkwasm.js is present in the build"
          else
            echo "gkwasm.js is missing from the build"
            exit 1
          fi
          if [ -f hugo-site/public/wasm/gkwasm_bg.wasm ]; then
            echo "gkwasm_bg.wasm is present in the build"
          else
            echo "gkwasm_bg.wasm is missing from the build"
            exit 1
          fi

      # Deploy the site to the gh-pages branch
      - name: Deploy Hugo Site
        env:
          HUGO_ENV: production
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-site/public  # Point to the correct directory
          cname: freenet.org
          force_orphan: true  # Create a new branch for clean deployment
          keep_files: false    # Replace existing files in the gh-pages branch
          exclude_assets: ''

      # Verify deployment by checking the gh-pages branch
      - name: Verify deployment
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of root directory in gh-pages branch:"
          ls -la
          echo "Contents of wasm directory in gh-pages branch:"
          ls -la wasm || echo "wasm directory not found"
          if [ ! -f wasm/gkwasm.js ] || [ ! -f wasm/gkwasm_bg.wasm ]; then
            echo "WebAssembly files are missing from the gh-pages branch"
            exit 1
          fi
