name: Freenet Deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Cache Hugo resources
        uses: actions/cache@v3
        env:
          cache-name: cache-hugo-resources
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Add WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-pack and wasm-bindgen-cli
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cargo install wasm-bindgen-cli

      - name: Install cargo-make
        run: cargo install --debug cargo-make

      - name: Build Site
        run: cargo make build-site

      - name: Debug WebAssembly files
        run: |
          echo "Contents of hugo-site/static/wasm:"
          ls -la hugo-site/static/wasm
          echo "Contents of hugo-site/public/wasm:"
          ls -la hugo-site/public/wasm
          echo "Contents of hugo-site/public:"
          ls -la hugo-site/public

      - name: Verify WebAssembly files in build
        run: |
          if [ ! -f hugo-site/public/wasm/gkwasm.js ]; then
            echo "gkwasm.js is missing from the build"
            exit 1
          fi
          if [ ! -f hugo-site/public/wasm/gkwasm_bg.wasm ]; then
            echo "gkwasm_bg.wasm is missing from the build"
            exit 1
          fi

      - name: Deploy Hugo Site
        env:
          HUGO_ENV: production
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./hugo-site/public
          cname: freenet.org
