name: Integration Tests

on:
  workflow_dispatch:

#  pull_request:
#    branches: [main]
#  push:
#    branches: [main]
#  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Hugo for static site generation
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Install wasm-pack and wasm-bindgen-cli
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cargo install -f wasm-pack
          cargo install -f wasm-bindgen-cli

      - name: Install Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run integration tests
        run: |
          export DISPLAY=:99
          cargo make integration-test