name: Integration Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Install wasm-pack and wasm-bindgen-cli
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          cargo install -f wasm-pack
          cargo install -f wasm-bindgen-cli

      - name: Install Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver

      - name: Run integration tests
        run: cargo make integration-test

      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: rust/integration_test/screenshots
